n = input('digite o que deseja: ')
print('O tipo desse valor é: ', type(n))
print('Só tem espaços? ' , n.isspace())
print('é um número? ', n.isnumeric())
print('é alfabético? ', n.isalpha())
print('é alfanumérico? ', n.isalnum())
print('Está em minúsculo? ', n.islower())
print('Está em maiúsculo? ', n.isupper())
print('Está capitalizada? ', n.istitle())
